Use new references API, update TF provider.
abbeylabs/abbey-starter-kit-okta pull request #3
Opened 2023-12-20 22:59 UTC by jeffchao

2023-12-20 22:59 UTC, jeffchao commented
Current dependencies on/for this PR:
* `main`
  * **PR #3** <a href="https://app.graphite.dev/github/pr/abbeylabs/abbey-starter-kit-okta/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/abbeylabs/abbey-starter-kit-okta/3?utm_source=stack-comment).

2023-12-21 21:41 UTC, Koshroy-Abbey requested changes

2023-12-21 21:41 UTC, Koshroy-Abbey commented on main.tf
> +      resource "okta_user_group_memberships" "has_nice_things__{{ .user.okta.user_id }}" { # {{ .user.abbey.email }}
`.user.email`

2023-12-21 23:03 UTC, Koshroy-Abbey approved these changes

2023-12-22 02:16 UTC, merged